version: '3.8'
services:
  server:
    image: 'arm64v8/nginx:stable-alpine'
    ports:
      - '8000:80' #nginix image exposes port 80
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
  php:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.php
    volumes:
      - ./src:/var/www/html:delegated
  mysql:
    platform: linux/x86_64
    image: mysql/mysql-server:8.0
    env_file:
      - ./env/mysql.env
  composer:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.composer
    volumes:
      - ./src:/var/www/html
  artisan:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.php
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
  npm:
    image: node:14
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      - ./src:/var/www/html
